server:
  port: 80

spring:
  application:
    name: project-web-80
  main:
    allow-bean-definition-overriding: true

eureka:
  instance:
    instance-id: project-web-80
    prefer-ip-address: true
  client:
    #fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.mapei.com:7001/eureka/,http://eureka7002.mapei.com:7002/eureka/ #Eureka地址

feign:
  hystrix:
    enabled: true # fegin默认关闭hystrix服务


info:
  app.name: mapei-springCloud-demo
  company.name: www.mapei.com
  build.artifactId: ${project.artifactId}
  build.version:  ${project.version}