server:
  port: 80

spring:
  application:
    name: project-web-80


eureka:
  instance:
    instance-id: project-web-80
    prefer-ip-address: true
  client:
    #fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka.mapei.com:7001/eureka/ #Eureka地址

info:
  app.name: mapei-springCloud-demo
  company.name: www.mapei.com
  build.artifactId: ${project.artifactId}
  build.version:  ${project.version}