server:
  port: 80

spring:
  application:
    name: project-web-80
  main:
    allow-bean-definition-overriding: true
  thymeleaf:
    enabled: true  #开启thymeleaf视图解析
    encoding: utf-8  #编码
    prefix: classpath:/templates/  #前缀
    cache: false  #是否使用缓存
    mode: HTML  #严格的HTML语法模式
    suffix: .html  #后缀名

logging:
  file:
    path: src/main/resources/log
  level:
    root: info

eureka:
  instance:
    instance-id: project-web-80
    prefer-ip-address: true
  client:
    #fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.mapei.com:7001/eureka/,http://eureka7002.mapei.com:7002/eureka/ #Eureka地址

feign:
  hystrix:
    enabled: true # fegin默认关闭hystrix服务


info:
  app.name: mapei-springCloud-demo
  company.name: www.mapei.com
  build.artifactId: ${project.artifactId}
  build.version:  ${project.version}