server:
  port: 8001
  
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.mapei.www.entity    # 所有Entity别名类所在包
  mapper-locations: classpath:mybatis/mapper/**/*.xml                       # mapper映射文件
  map-underscore-to-camel: true


spring:
   application:
    name: project-user-8001
   datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver          # mysql驱动包
    url: jdbc:mysql://127.0.0.1/springBoot_myBatis_shiro?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false&useAffectedRows=true&allowMultiQueries=true              # 数据库名称
    username: root
    password: mapei123
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间


eureka:
  instance:
    instance-id: project-user-8001
    prefer-ip-address: true
  client:
    #fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka.mapei.com:7001/eureka/ #Eureka地址


info: 
  app.name: mapei-springCloud-demo
  company.name: www.mapei.com
  build.artifactId: ${project.artifactId}
  build.version:  ${project.version}

