server:
  port: 9501

spring:
  application:
    name: project-zuul-gateway-9501

eureka:
  instance:
    instance-id: project-zuul-gateway-9501
    prefer-ip-address: true
  client:
    #fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.mapei.com:7001/eureka/,http://eureka7002.mapei.com:7002/eureka/ #Eureka地址


zuul:
  prefix: /gateway
  ignored-services: "*"
  routes:
    mydept.serviceId: project-user-8001
    mydept.path: /user/**


info:
  app.name: mapei-springCloud-demo
  company.name: www.mapei.com
  build.artifactId: ${project.artifactId}
  build.version:  ${project.version}

